### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by mynenik**
@certik Please review the changes made by these three commits, which provide a working make_atsp script, a bin sudirectory for the executables, and changes to example scripts so that they work under the new directory structure. The bin subdirectory is used in the later distributions of atsp, such as atsp-book and atsp2K.

If you're ok with these changes I can merge them into the master.

### CODE REVIEW

**Comment by certik** [comment]
This is fine with me. Do you want to move this repository to its own organization? The reason I am asking is that we should also setup an automatic CI, e.g. using Travis, and it's better to move the repository first, and then set it up, then first set it up and then move it.

**Comment by mynenik** [comment]
I have no objections to moving the repository to its own organization. I don't know much about automatic configuration or Travis. I'm only familiar with the configure-make process typical for Linux source packages, but even then not much when it comes to the configure part. Also, my interests at present are to ensure that the programs for fine structure, hyperfine structure, and isotope shift calculations are all working per the CAS book's examples and related publications. So, if you think that putting the project out on its own organization is a good idea to bring in others who can contribute, it's fine with me. First, we should state the current working goals of the project. For me, it is to have a version of the ATSP code which builds readily on a GNU Linux system and provides scripts to run the essential examples from the CAS book, and other scripts released by the original authors.

**Comment by certik** [comment]
@mynenik I think this is a worthy goal. Let's make it happen. I'll work on the transfer tomorrow.

**Comment by mynenik** [comment]
Ok. Please ignore any new commits on my fork for now. I'm having trouble with git. I need to resync my master to your present state.

**Pull request merged**
